version: '3.7'

x-logging: &loki-logging
  driver: loki
  options:
    loki-url: ${LOKI_URL}

volumes:
    prometheus_data: {}

networks:
  back-tier:

services:

  prometheus:
    image: prom/prometheus:v2.36.2
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - back-tier
    restart: always
    logging: *loki-logging

  promtail:
    image: grafana/promtail:1.4.1
    volumes:
      - ./promtail/:/etc/promtail/
    command: 
      - '-config.file=/etc/promtail/config.yml'
    environment:
      - LOKI_URL=${LOKI_URL}
    networks:
      - back-tier
    ports:
      - 1514:1514
      - 9080:9080
    restart: always
    logging: *loki-logging

  syslog-ng:
    image: lscr.io/linuxserver/syslog-ng:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
    volumes:
      - ./syslog-ng/:/config
      - /var/log:/var/log #optional
    ports:
      - 514:5514/udp
      - 601:6601/tcp
      - 6514:6514/tcp
    networks:
      - back-tier
    restart: unless-stopped
    logging: *loki-logging
    
  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /:/host:ro,rslave
    command: 
      - '--path.rootfs=/host'
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    networks:
      - back-tier
    restart: always
    logging: *loki-logging

  blackbox-exporter:
    image: prom/blackbox-exporter:master
    volumes:
      - ./blackbox/:/config
    command:
      - '--config.file=/config/blackbox.yml'
    networks:
      - back-tier
    # ports:
    #   - 9115:9115
    restart: always
    logging: *loki-logging

  apcupsd-exporter:
    image: hhhzzzhou/apcupsd-exporter:latest
    command: "-apcupsd.addr host.docker.internal:3551"
    extra_hosts:
        host.docker.internal: host-gateway
    # ports:
    #   - 9162:9162
    networks:
      - back-tier
    restart: always
    logging: *loki-logging

  ping-exporter:
    image: czerwonk/ping_exporter:latest
    volumes:
      - ./pingexporter/:/config:ro
    # ports:
    #   - 9427:9427
    networks:
      - back-tier
    restart: always
    logging: *loki-logging